---

- name: install collabora app
  shell: '{{ docker_occ_cmd }} app:install richdocuments'
  args:
    creates: '{{ nextcloud_www_dir }}/apps/richdocuments'
  register: install_collabora_app
  failed_when: false
  
- name: enable collabora app
  shell: '{{ docker_occ_cmd }} app:enable richdocuments'
  when: install_collabora_app is changed

- name: set collabora wopi url
  shell: '{{ docker_occ_cmd }} config:app:set richdocuments wopi_url --value {{ nc_config_collabora_url }}'
  when: install_collabora_app is changed
