---
- name: Updating oidc configs
  set_fact:
    oidc_config_default: "{{ oidc_config_default|combine(oidc_config) }}"
    oidc_login_attributes_default: "{{ oidc_login_attributes_default|combine(oidc_login_attributes) }}"

- name: Ensure OIDC app state
  shell: "{{ docker_occ_cmd }} app:{{ 'enable' if oidc_enabled|bool else 'disable' }} oidc_login"

- name: Ensure OIDC social login is disabled, when using OIDC
  shell: "{{ docker_occ_cmd }} app:disable sociallogin"
  when: 
    - oidc_enabled|bool

- name: Ensure OIDC login settings
  shell: "{{ docker_occ_cmd }} config:system:set oidc_login_attributes {{ item.key }} --value='{{ item.value }}'"
  loop: "{{ lookup('dict', oidc_login_attributes_default) }}"
  when: 
    - oidc_enabled|bool

- name: Ensure OIDC settings
  shell: "{{ docker_occ_cmd }} config:system:set {{ item.key }} --value='{{ item.value.value }}' --type={{ item.value.type }}"
  loop: "{{ lookup('dict', oidc_config_default) }}"
  when: 
    - oidc_enabled|bool