---
- name: Copy theme
  ansible.builtin.copy:
    src: "{{ nextcloud_custom_theme }}"
    dest: "{{ project_root }}/data/nextcloud/themes/"
    owner: "{{ 82 if ( 'alpine' in tag_nextcloud ) else 33 }}"
    group: "{{ 82 if ( 'alpine' in tag_nextcloud ) else 33 }}"
    mode: '0755'

- name: Enable theme in config
  shell: "{{ docker_occ_cmd }} {{ item }}"
  loop:
    - "config:system:set theme --value='{{ nextcloud_custom_theme }}'"
    - "app:disable theming"