---
- name: init env
  template:
    src: "{{ item.file }}"
    dest: "{{ item.destination }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  become: yes
  loop:
    - { file: "env.j2", destination: "{{ project_root }}/.env", owner: "{{ server_user }}", mode: "0755" }
  notify:
    - compose down
    - compose up

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: compose down
  docker_compose:
    project_src: "{{ project_root }}"
    state: absent
  ignore_errors: yes

- name: docker build redis
  community.docker.docker_image:
    name: "redisbuildnc:{{ tag_redis }}"
    build:
      path: "{{ project_root }}/build"
      dockerfile: "Dockerfile_redis"
    source: build
  become: yes

- name: compose up
  docker_compose:
    project_src: "{{ project_root }}"
    state: present
    pull: no

- name: wait for nextcloud
  wait_for:
    host: "127.0.0.1"
    port: "{{ compose_config_tcp_port }}"

- name: first setup nextcloud
  shell: >
    sleep 1m; {{ docker_occ_cmd }} maintenance:install --admin-user {{ nextcloud_admin }} --admin-pass {{ compose_config_nc_admin_pw }} --data-dir {{ nextcloud_container_data_dir }}
  failed_when: False

- name: snap warning
  debug:
      msg: "Nextcloud files from a snap installation are found on your system. It is recommended to migrate to docker with the supported migration script and purge the snap installation from your system."