---
- name: init env
  template:
    src: "{{ item.file }}"
    dest: "{{ item.destination }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  become: yes
  loop:
    - { file: "env.j2", destination: "{{ project_root }}/.env", owner: "{{ server_user }}", mode: "0755" }
  notify:
    - compose down
    - compose up

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: compose down
  docker_compose:
    project_src: "{{ project_root }}"
    state: absent
  ignore_errors: yes

- name: compose up
  docker_compose:
    project_src: "{{ project_root }}"
    state: present
    pull: yes

- name: first setup nextcloud
  shell: >
    {{ docker_occ_cmd }} maintenance:install 
    --database {{ nextcloud_db_type }} --database-host {{ nextcloud_db_host }} --database-name {{ nextcloud_db_name }} 
    --database-user {{ nextcloud_db_user }} --database-pass {{ nextcloud_db_passwd }} 
    --admin-user {{ nextcloud_admin }} --admin-pass {{ compose_config_nc_admin_pw }} --data-dir {{ nextcloud_container_data_dir }}