---
# - name: Ensure snap packages present
#   snap:
#     name:
#       - rclone
#     state: "{% if rclone_snap_enabled|bool %}present{% else %}absent{% endif %}"
#   ignore_errors: yes

# - name: Ensure snaps are refreshed
#   shell: "snap refresh"
#   become: yes
#   changed_when: false

- name: Ensure system scripts
  template:
    src: "{{ item.file }}"
    dest: "{{ item.destination }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  become: yes
  loop:
    - { file: "rclone_sync.j2", destination: "/usr/local/bin/rclone_sync", owner: "root", mode: "0750" }
 
- name: Ensure rclone cron job
  cron:
    name: rclone sync
    minute: "{{ config_rclone_cron.minute }}"
    hour:   "{{ config_rclone_cron.hour }}"
    day:  "{{ config_rclone_cron.day }}"
    month: "{{ config_rclone_cron.month }}"
    user: root
    job: "/usr/local/bin/rclone_sync > /dev/null 2>&1"
    cron_file: rclone_sync
    state: "{% if config_cron_enabled|bool %}present{% else %}absent{% endif %}"

- name: Flush handlers
  meta: flush_handlers