---
config_update_dist: true

config_restic_path: '/snap/bin/restic'

config_restic_prune_policy: '--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 1'

config_cron_job: { month: "*", day: "*", hour: "2", minute: "30" }
job_list: []

gotify_notify_dest: []
  # - {host: "", key: ""}

default_apt_packages:
  - byobu
  - zsh
  - curl
  - wget
  - dnsutils
  - git
  - sudo
  - htop
  - vim
  - nano
  - openssh-server
  - zip
  - unzip
  - dos2unix
  - screen
  - ncdu
  - bmon
  - nmap
  - snapd
  - htop
  - powertop
  - pwgen
  - wipe
  - sshfs
  - rkhunter
  - chkrootkit
  - davfs2