---
# mailserver release. Set to 'stable' to track the stable branch.
mailserver_release: RELEASE
# ensure docker-compose gets restarted on every run
restart_compose: false
# default mailserver user
default_user: postmaster
# setting deploy directory
project_root: /srv/mailserver
# mailserver user
mailserver_user: root
# mailserver configs
config_fail2ban: 1
config_log_trigger: daily_cron
config_postmaster: 
config_message_limit: 102400000

traefik_letsencrypt_dir: './letsencrypt'

compose_ports:
  - { bind: "", host: "25", container: "25/tcp" }
  - { bind: "", host: "143", container: "143/tcp" }
  - { bind: "", host: "587", container: "587/tcp" }
  - { bind: "", host: "993", container: "993/tcp" }

compose_extra_ports: []
  # - { bind: "", host: "4190", container: "4190" }

compose_config_env: []
  # - { var: "ENABLE_MANAGESIEVE", val: "1" }

compose_extra_volumes: []
  # - "./extravolume:/path/in/my/container"

mailserver_users: []
  # - { user: "testuser", pw: "verysikrit", alias: "useralias" }

### TRAEFIK
traefik_mailserver_enabled: False
traefik_mailserver_proxy_enabled: False

## DNS ENTRie
dns_entries_mailserver:
  spf: "v=spf1 mx ~all"
  dmarc: "v=DMARC1; p=none;"

## custom config files

mailserver_custom_config_files:
  postfix-main: "{{ project_root }}/config/postfix-main.cf"
  postfix-master: "{{ project_root }}/config/postfix-master.cf"
  dovecot: "{{ project_root }}/config/dovecot.cf"

