---
- name: ensure compose down
  docker_compose:
    project_src: "{{ project_root }}"
    state: absent
  ignore_errors: yes
  when: compose_file.stat.exists

- name: ensure ssh key
  user:
    name: git
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    state: present
  notify:
    - ensure app gitea folder
    - init templates

- name: ensure app gitea folder
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { path: "/app/gitea", owner: "root", mode: "755" }

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: compose down
  docker_compose:
    project_src: "{{ project_root }}"
    state: absent
  ignore_errors: yes

- name: compose up
  docker_compose:
    project_src: "{{ project_root }}"
    state: present
    pull: yes