---
- name: Install nextcloud snap
  command: snap install nextcloud
  become: yes
  register: nc_install_return
  failed_when: False
  changed_when: '"is already installed" not in nc_install_return.stderr'
  notify:
    - init pw
    - init user
    - print password
    
- name: Flush handlers
  meta: flush_handlers

- name: Ensure nextcloud configs
  shell:
    cmd: "{{ item }}" 
  become: yes
  loop: "{{ config_nextcloud_cmds }}"
  notify:
    - reload apache

- name: Ensure nextcloud nginx conf is present
  template:
    src: nextcloud.nginx
    dest: "/etc/nginx/{{ nginx_domain_name }}.d/nextcloud.conf"
  notify: reload nginx

