---
# docker image tags
tag_nextcloud: '22.2.0-fpm-alpine'
tag_redis: '6.2.6'
tag_mariadb: '10.5'
tag_nginx: 'latest'
tag_calbackup: 'latest'

# nginx fpm config
config_nginx_fpm: "https://raw.githubusercontent.com/nextcloud/docker/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf"

# ensure docker-compose gets restarted on every run
restart_compose: false
# docker-compose project name
docker_config_project: nextcloud
# start docker by default
start_compose: true
# running user
server_user: root
# project root
project_root: "/srv/{{ docker_config_project }}"
nextcloud_www_dir: "{{ project_root }}/data/nextcloud"
calbackup_dir: "{{ project_root }}/data/calbackup"
nextcloud_database_dump_dir: "{{ project_root }}/db_backup"
compose_executable: "/usr/local/bin/docker-compose"
compose_base_cmd: "{{ compose_executable }} -f {{ project_root }}/docker-compose.yml exec -T"
docker_occ_cmd: "{{ compose_base_cmd }} --user www-data app php occ"
docker_php_cmd: "{{ compose_base_cmd }} --user www-data app php -f cron.php"

# public domain of the server
nginx_domain_name: 
config_deploy_nginx_config: true
# Docker-compose configs
compose_config_startup: always
compose_config_mysql_pw: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
compose_config_mysql_root_pw: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
compose_config_nc_admin_pw: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

nc_config_trusted_proxy: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
online_office: 'collabora'
fulltextsearch_enabled: false

enable_calbackup: true

compose_extra_volumes: []
  # - { host: "./data/test", container: "/test", mode: ":ro" } 

# Database

nextcloud_db_type: 'mysql'
nextcloud_db_host: 'db'
nextcloud_db_name: 'nextcloud'
nextcloud_db_user: 'nextcloud'
nextcloud_db_passwd: "{{ compose_config_mysql_pw }}"
nextcloud_db_prefix: 'oc_'

nextcloud_container_data_dir:  '/var/www/html/data'

# BACKUPs

backup_jobs: []
config_backups_enabled: true
config_backup_cron: { month: "*", day: "*", hour: "3", minute: "0" }

# php configs
nc_config_php_upload_limit: '512M'
nc_config_php_memory_limit: '512M'
nc_config_php_max_execution_time: '7000'

# env
nc_config_collabora_url: "https://{{ nginx_domain_name }}:443"

compose_config_tcp_port: "81"
compose_config_env:
  - { var: "MYSQL_HOST", val: "db" }
  - { var: "REDIS_HOST", val: "redis" }
  - { var: "NEXTCLOUD_TRUSTED_DOMAINS", val: "{{ nginx_domain_name }}" }
  - { var: "OVERWRITEHOST", val: "{{ nginx_domain_name }}" }
  - { var: "TRUSTED_PROXIES", val: "{{ nc_config_trusted_proxy }}" }
  - { var: "OVERWRITEPROTOCOL", val: "https" }
  - { var: "NEXTCLOUD_ADMIN_USER", val: "admin" }
  - { var: "PHP_MEMORY_LIMIT", val: "{{ nc_config_php_memory_limit }}" }
  - { var: "PHP_UPLOAD_LIMIT", val: "{{ upload_limit|default(nc_config_php_upload_limit) }}" }

nextccloud_system_config:
  - "overwrite.cli.url --value=https://{{ nginx_domain_name }}"
  - "trusted_domains 0 --value={{ nginx_domain_name }}"
  - "trusted_proxies 0 --value={{ nc_config_trusted_proxy }}"
  - "trusted_proxies 1 --value=127.0.0.1"
  - "forwarded_for_headers 0 --value='X-Forwarded-For'"
  - "forwarded_for_headers 1 --value='HTTP_X_FORWARDED_FOR'"
  - "redis host --value='redis'"
  - "redis port --value='6379' --type=integer"
  - "redis timeout --value='0' --type=integer"
  - "memcache.local --value='\\OC\\Memcache\\Redis'"
  - "memcache.locking --value='\\OC\\Memcache\\Redis'"
  - "filelocking.enabled --value=true --type=boolean"
  - "enable_previews --value=true --type=boolean"
  - "enabledPreviewProviders 0 --value='OC\\Preview\\PNG'"
  - "enabledPreviewProviders 1 --value='OC\\Preview\\JPEG'"
  - "enabledPreviewProviders 2 --value='OC\\Preview\\GIF'"
  - "enabledPreviewProviders 3 --value='OC\\Preview\\BMP'"
  - "enabledPreviewProviders 4 --value='OC\\Preview\\XBitmap'"
  - "enabledPreviewProviders 5 --value='OC\\Preview\\MarkDown'"
  - "enabledPreviewProviders 6 --value='OC\\Preview\\MP3'"
  - "enabledPreviewProviders 7 --value='OC\\Preview\\TXT'"
  - "enabledPreviewProviders 8 --value='OC\\Preview\\Illustrator'"
  - "enabledPreviewProviders 9 --value='OC\\Preview\\Movie'"
  - "enabledPreviewProviders 10 --value='OC\\Preview\\MSOffice2003'"
  - "enabledPreviewProviders 11 --value='OC\\Preview\\MSOffice2007'"
  - "enabledPreviewProviders 12 --value='OC\\Preview\\MSOfficeDoc'"
  - "enabledPreviewProviders 13 --value='OC\\Preview\\OpenDocument'"
  - "enabledPreviewProviders 14 --value='OC\\Preview\\PDF'"
  - "enabledPreviewProviders 15 --value='OC\\Preview\\Photoshop'"
  - "enabledPreviewProviders 16 --value='OC\\Preview\\Postscript'"
  - "enabledPreviewProviders 17 --value='OC\\Preview\\StarOffice'"
  - "enabledPreviewProviders 18 --value='OC\\Preview\\SVG'"
  - "enabledPreviewProviders 19 --value='OC\\Preview\\TIFF'"
  - "enabledPreviewProviders 20 --value='OC\\Preview\\Font'"
  - "preview_max_x --value='1024' --type=integer"
  - "preview_max_y --value='768' --type=integer"
  - "preview_max_scale_facto --value='1' --type=integer"
  - "auth.bruteforce.protection.enabled --value=true --type=boolean"
  - "trashbin_retention_obligation --value='auto,7'"
  - "skeletondirectory --value=''"
  - "defaultapp --value='file'"
  - "activity_expire_days --value='14'  --type=integer"
  - "integrity.check.disabled --value=false --type=boolean"
  - "updater.release.channel --value=stable"
  - "loglevel --value=1 --type=integer"
  - "maintenance --value=false --type=boolean"
  - "theme --value=''"
  - "default_phone_region --value='DE'"

nextcloud_configure_mail: false

nextccloud_mail_config:
  - {key: "mail_from_address", type: "string", value: "{{ nextcloud_mail_from }}" }
  - {key: "mail_domain", type: "string", value: "{{ nextcloud_mail_domain }}" }
  - {key: "mail_smtphost", type: "string", value: "{{ nextcloud_mail_smtphost }}" }
  - {key: "mail_smtpname", type: "string", value: "{{ nextcloud_mail_smtpname }}" }
  - {key: "mail_smtppassword", type: "string", value: "{{ nextcloud_mail_smtppwd }}" }
  # Default values
  - {key: "mail_smtpsecure", type: "string", value: "{{ nextcloud_mail_smtpsecure|default('tls') }}" }
  - {key: "mail_smtpmode", type: "string", value: "{{ nextcloud_mail_smtpmode|default('smtp') }}" }
  - {key: "mail_sendmailmode", type: "string", value: "{{ nextcloud_mail_sendmailmode|default('smtp') }}" }
  - {key: "mail_smtpauth", type: "boolean", value: "{{ nextcloud_mail_smtpauth|default('true') }}" }
  - {key: "mail_smtpport", type: "string", value: "{{ nextcloud_mail_smtpport|default('587') }}" }
  - {key: "mail_smtpauthtype", type: "string", value: "{{ nextcloud_mail_smtpauthtype|default('LOGIN') }}" }

nextcloud_app_config:
  - {name: "survey_client", state: "disable"}
  - {name: "firstrunwizard", state: "disable"}
  - {name: "admin_audit", state: "enable"}
  - {name: "files_pdfviewer", state: "enable"}
  - {name: "sharebymail", state: "enable"}
  - {name: "registration", state: "enable"}


  