---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: compose down
  community.docker.docker_compose_v2:
    project_src: "{{ project_root }}"
    state: absent

- name: compose up
  community.docker.docker_compose_v2:
    project_src: "{{ project_root }}"
    state: present
    pull: missing


