---
# cryptpad release.
docker_release: 
# running user
server_user: root
# project root
project_root: /srv/kuma
# public domain
nginx_domain_name: 
# compose restart state
restart_compose: false
# docker-compose project name
docker_config_project: uptimekuma
# start docker by default
start_compose: true
# tcp port
config_tcp: 3421