---
- name: Check .env file
  stat:
    path: "{{ project_root }}/.env"
  register: env_file
  changed_when: not env_file.stat.exists
  notify:
    - init env

###################################################################################

- name: Query kutt tags from github
  uri:
    url: https://api.github.com/repos/thedevs-network/kutt/tags
    return_content: true
  register: kutt_github_tags
  ignore_errors: yes

- name: Registering release tag
  set_fact:
    tag_kutt:  "{{ (kutt_github_tags.json  | rejectattr('name', 'contains', '-') | selectattr('name', 'contains', 'v') | list)[0]['name'] }}"
  when: (tag_kutt == None)

###################################################################################

- name: Ensure directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: directory
    recurse: "{{ item.r }}"
  loop:
    - { path: "{{ project_root }}", owner: "{{ server_user }}", r: "no" }
    - { path: "{{ base_build_dir }}", owner: "root", r: "no" }

- name: Ensure nginx template
  template:
    src: "{{ item.file }}"
    dest: "{{ item.destination }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - { file: "nginx.j2", destination: "/etc/nginx/{{ nginx_domain_name }}.d/nginx.conf", owner: "root", mode: "0644" }
  become: yes
  when: ( nginx_domain_name != None and not traefik_enabled|default (False))
  notify:
    - reload nginx

- import_tasks: build.yml
  when: build_kutt

- name: init templates
  template:
    src: "{{ item.file }}"
    dest: "{{ item.destination }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  become: yes
  loop:
    - { file: "docker-compose.j2", destination: "{{ project_root }}/docker-compose.yml", owner: "{{ server_user }}", mode: "0755" }
  notify:
    - compose down
    - compose up

- name: Compose startup state
  assert: { that: true, quiet: true }
  changed_when: true
  notify:
    - compose up
  when: start_compose|bool

- name: Flush handlers
  meta: flush_handlers
