---


- name: Ensure cloudflared
  block:
  - name: Ensure key states (curl)
    get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
    loop: "{{ config_apt_keys_curl }}"
    ignore_errors: yes

  - name: Ensure source states
    apt_repository:
      repo: "{{ item.repo }}"
      state: "present"
      filename: "{{ item.filename }}"
      update_cache: true
    loop: "{{ config_apt_sources }}"

  - name: Ensure apt packages
    apt:
      name:
        - cloudflared
      state: latest
      update_cache: yes
      install_recommends: yes

  rescue:
  - name: Ensure source states
    apt_repository:
      repo: "{{ item.repo }}"
      state: "absent"
      filename: "{{ item.filename }}"
      update_cache: true
    loop: "{{ config_apt_sources }}"

  - name: Ensure cloudflared over .deb
    apt:
      deb: "{{ config_cloudflared_deb_url }}"
    ignore_errors: yes